<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>dev.thatonedev.companion</AssemblyName>
    <RootNamespace>dev.thatonedev.companion</RootNamespace>
    <LangVersion>latest</LangVersion>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MiraAPI">
      <HintPath>libs\MiraAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
