<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>dev.thatonedev.companion</AssemblyName>
    <RootNamespace>dev.thatonedev.companion</RootNamespace>
    <LangVersion>latest</LangVersion>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <!-- Pulls in BepInEx and IL2CPP targets for Among Us modding -->
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MiraAPI">
      <HintPath>libs\MiraAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
